--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/artix-nord.png"

-- Special
background="#1b1e25"
foreground="#c6c6c8"
cursor="#c6c6c8"

-- Colors
color0="#1b1e25"
color1="#738C90"
color2="#7DA2A4"
color3="#96A5A8"
color4="#8FBBBA"
color5="#95C0BF"
color6="#A8BFC0"
color7="#c6c6c8"
color8="#626878"
color9="#738C90"
color10="#7DA2A4"
color11="#96A5A8"
color12="#8FBBBA"
color13="#95C0BF"
color14="#A8BFC0"
color15="#c6c6c8"
