$foreground = rgb(c6c6c8)
$color0 = rgb(1b1e25)
$color1 = rgb(50637B)
$color2 = rgb(576F8C)
$color3 = rgb(5D7FA9)
$color4 = rgb(607FA6)
$color5 = rgb(66899C)
$color6 = rgb(5F81A9)
$color7 = rgb(c6c6c8)
$color8 = rgb(626878)
$color9 = rgb(50637B)
$color10 = rgb(576F8C)
$color11 = rgb(5D7FA9)
$color12 = rgb(607FA6)
$color13 = rgb(66899C)
$color14 = rgb(5F81A9)
$color15 = rgb(c6c6c8)