# Shell variables
# Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/ign-0001.png"

# Special
background='#12171f'
foreground='#c3c5c7'
cursor='#c3c5c7'

# Colors
color0='#12171f'
color1='#6E91AF'
color2='#7496AC'
color3='#7CA8C2'
color4='#8DA2B4'
color5='#9AB5C7'
color6='#B4C7D5'
color7='#c3c5c7'
color8='#5e6772'
color9='#6E91AF'
color10='#7496AC'
color11='#7CA8C2'
color12='#8DA2B4'
color13='#9AB5C7'
color14='#B4C7D5'
color15='#c3c5c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
