$foreground = rgb(c3c6c7)
$color0 = rgb(101c21)
$color1 = rgb(91545F)
$color2 = rgb(A95A66)
$color3 = rgb(BE616B)
$color4 = rgb(C15F6C)
$color5 = rgb(C4656C)
$color6 = rgb(CF886F)
$color7 = rgb(c3c6c7)
$color8 = rgb(5e6d72)
$color9 = rgb(91545F)
$color10 = rgb(A95A66)
$color11 = rgb(BE616B)
$color12 = rgb(C15F6C)
$color13 = rgb(C4656C)
$color14 = rgb(CF886F)
$color15 = rgb(c3c6c7)