# Shell variables
# Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/CRON-Nord.png"

# Special
background='#1b1e25'
foreground='#c6c6c8'
cursor='#c6c6c8'

# Colors
color0='#1b1e25'
color1='#658185'
color2='#688589'
color3='#6E8E91'
color4='#6F8E91'
color5='#7B9FA0'
color6='#7DA2A4'
color7='#c6c6c8'
color8='#626878'
color9='#658185'
color10='#688589'
color11='#6E8E91'
color12='#6F8E91'
color13='#7B9FA0'
color14='#7DA2A4'
color15='#c6c6c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
