--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/ign-0001.png"

-- Special
background="#12171f"
foreground="#c3c5c7"
cursor="#c3c5c7"

-- Colors
color0="#12171f"
color1="#6E91AF"
color2="#7496AC"
color3="#7CA8C2"
color4="#8DA2B4"
color5="#9AB5C7"
color6="#B4C7D5"
color7="#c3c5c7"
color8="#5e6772"
color9="#6E91AF"
color10="#7496AC"
color11="#7CA8C2"
color12="#8DA2B4"
color13="#9AB5C7"
color14="#B4C7D5"
color15="#c3c5c7"
