--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/BirdNord.png"

-- Special
background="#181b22"
foreground="#c5c6c7"
cursor="#c5c6c7"

-- Colors
color0="#181b22"
color1="#68787E"
color2="#537E82"
color3="#767D83"
color4="#7D8288"
color5="#85898E"
color6="#9A9EA2"
color7="#c5c6c7"
color8="#606676"
color9="#68787E"
color10="#537E82"
color11="#767D83"
color12="#7D8288"
color13="#85898E"
color14="#9A9EA2"
color15="#c5c6c7"
