# Shell variables
# Generated by 'wal'
wallpaper="/home/xyphe/.wallpapers/BirdNord.png"

# Special
background='#181b22'
foreground='#c5c6c7'
cursor='#c5c6c7'

# Colors
color0='#181b22'
color1='#68787E'
color2='#537E82'
color3='#767D83'
color4='#7D8288'
color5='#85898E'
color6='#9A9EA2'
color7='#c5c6c7'
color8='#606676'
color9='#68787E'
color10='#537E82'
color11='#767D83'
color12='#7D8288'
color13='#85898E'
color14='#9A9EA2'
color15='#c5c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
