foreground         #c3c6c7
background         #101c21
background_opacity 1.0
cursor             #c3c6c7

active_tab_foreground     #101c21
active_tab_background     #c3c6c7
inactive_tab_foreground   #c3c6c7
inactive_tab_background   #101c21

active_border_color   #c3c6c7
inactive_border_color #101c21
bell_border_color     #91545F

color0       #101c21
color8       #5e6d72
color1       #91545F
color9       #91545F
color2       #A95A66
color10      #A95A66
color3       #BE616B
color11      #BE616B
color4       #C15F6C
color12      #C15F6C
color5       #C4656C
color13      #C4656C
color6       #CF886F
color14      #CF886F
color7       #c3c6c7
color15      #c3c6c7
