[colors]
background = '#1b1e258e'
black = '#1b1e25'
blue = '#50637B'
cursor = '#c6c6c8'
cyan = '#576F8C'
foreground = '#c6c6c8'
green = '#5D7FA9'
magenta = '#607FA6'
red = '#66899C'
tabs = '#c6c6c8'
tabs-active = '#5F81A9'
white = '#c6c6c8'
yellow = '#c6c6c8'
dim-black = '#1b1e258e'
dim-blue = '#50637B8e'
dim-cyan = '#576F8C8e'
dim-foreground = '#c6c6c88e'
dim-green = '#5D7FA98e'
dim-magenta = '#607FA68e'
dim-red = '#66899C8e'
dim-white = '#5F81A98e'
dim-yellow = '#c6c6c88e'
light-black = '#50637B'
light-blue = '#576F8C'
light-cyan = '#5D7FA9'
light-foreground = '#607FA6'
light-green = '#66899C'
light-magenta = '#5F81A9'
light-red = '#c6c6c8'
light-white = '#50637B'
light-yellow = '#576F8C'
