[colors]
background = '#101c218e'
black = '#101c21'
blue = '#91545F'
cursor = '#c3c6c7'
cyan = '#A95A66'
foreground = '#c3c6c7'
green = '#BE616B'
magenta = '#C15F6C'
red = '#C4656C'
tabs = '#c3c6c7'
tabs-active = '#CF886F'
white = '#c3c6c7'
yellow = '#c3c6c7'
dim-black = '#101c218e'
dim-blue = '#91545F8e'
dim-cyan = '#A95A668e'
dim-foreground = '#c3c6c78e'
dim-green = '#BE616B8e'
dim-magenta = '#C15F6C8e'
dim-red = '#C4656C8e'
dim-white = '#CF886F8e'
dim-yellow = '#c3c6c78e'
light-black = '#91545F'
light-blue = '#A95A66'
light-cyan = '#BE616B'
light-foreground = '#C15F6C'
light-green = '#C4656C'
light-magenta = '#CF886F'
light-red = '#c3c6c7'
light-white = '#91545F'
light-yellow = '#A95A66'
