[colors.primary]
background = "#101c21"
foreground = "#c3c6c7"

[colors.cursor]
text = "#101c21"
cursor = "#c3c6c7"

[colors.vi_mode_cursor]
text = "#101c21"
cursor = "#c3c6c7"

[colors.search.matches]
foreground = "#101c21"
background = "#c3c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6d72"
background = "#c3c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#101c21"
red = "#91545F"
green = "#A95A66"
yellow = "#BE616B"
blue = "#C15F6C"
magenta = "#C4656C"
cyan = "#CF886F"
white = "#c3c6c7"

[colors.bright]
black = "#5e6d72"
red = "#91545F"
green = "#A95A66"
yellow = "#BE616B"
blue = "#C15F6C"
magenta = "#C4656C"
cyan = "#CF886F"
white = "#c3c6c7"

[colors.dim]
black = "#c3c6c7"
red = "#91545F"
green = "#C4656C"
yellow = "#BE616B"
blue = "#C15F6C"
magenta = "#A95A66"
cyan = "#CF886F"
white = "#5e6d72"

