# pywal theme for ghostty

background = 1b1e25
foreground = c6c6c8
cursor-color = c6c6c8
selection-background = c6c6c8
selection-foreground = 1b1e25

palette = 0=#1b1e25
palette = 1=#50637B
palette = 2=#576F8C
palette = 3=#5D7FA9
palette = 4=#607FA6
palette = 5=#66899C
palette = 6=#5F81A9
palette = 7=#c6c6c8
palette = 8=#626878
palette = 9=#50637B
palette = 10=#576F8C
palette = 11=#5D7FA9
palette = 12=#607FA6
palette = 13=#66899C
palette = 14=#5F81A9
palette = 15=#c6c6c8
