# pywal theme for ghostty

background = 101c21
foreground = c3c6c7
cursor-color = c3c6c7
selection-background = c3c6c7
selection-foreground = 101c21

palette = 0=#101c21
palette = 1=#91545F
palette = 2=#A95A66
palette = 3=#BE616B
palette = 4=#C15F6C
palette = 5=#C4656C
palette = 6=#CF886F
palette = 7=#c3c6c7
palette = 8=#5e6d72
palette = 9=#91545F
palette = 10=#A95A66
palette = 11=#BE616B
palette = 12=#C15F6C
palette = 13=#C4656C
palette = 14=#CF886F
palette = 15=#c3c6c7
