[ColorScheme]
active_colors=#c3c6c7
inactive_colors=#5e6d72
disabled_colors=#5e6d72
window=#101c21
windowText=#c3c6c7
base=#101c21
text=#c3c6c7
button=#101c21
buttonText=#c3c6c7
highlight=#CF886F
highlightText=#101c21
link=#C15F6C
linkVisited=#C4656C
